### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe in train.py

### ISSUE THREAD

**Issue by padmalcom** [ksw0306/FloWaveNet#4]
Hi, I'm on a Windows 10 system with anaconda and python 3.6. I ran the preprocessing succesfully but on calling train.py I get the following error. This issues is definitely related to windows (see https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing) but I don't know how to solve it.

```
(FloWaveNet) C:\Users\admin\FloWaveNet>python train.py --model_name flowavenet --batch_size 8 --n_block 8 --n_flow 6 --n_layer 2 --causal no
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\FloWaveNet\train.py", line 228, in <module>
    training_epoch_loss = train(epoch, model, optimizer)
  File "C:\Users\admin\FloWaveNet\train.py", line 91, in train
    for batch_idx, (x, c) in enumerate(train_loader):
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\context.py", line 322, in _Popen
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    return Popen(process_obj)
    training_epoch_loss = train(epoch, model, optimizer)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
  File "train.py", line 91, in train
    prep_data = spawn.get_preparation_data(process_obj._name)
    for batch_idx, (x, c) in enumerate(train_loader):
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    return _DataLoaderIter(self)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    _check_not_importing_main()
    w.start()
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\process.py", line 105, in start
    is not going to be frozen to produce an executable.''')
    self._popen = self._Popen(self)
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\context.py", line 223, in _Popen

    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\Anaconda3\envs\FloWaveNet\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by L0SG** [comment]
We've [commited](https://github.com/ksw0306/FloWaveNet/commit/3d0b1685799e6f76dea9bd5e413601b623c94891) a little modification that will also run fine on Windows. Wrapping the main script with `if __name__ == '__main__'` is needed since Windows does not support `fork()` in Linux systems AFAIK.
