### ISSUE TITLE
RuntimeError: CUDA error: out of memory in train.py

### ISSUE THREAD

**Issue by padmalcom** [ksw0306/FloWaveNet#7]
Hi, I get an out of memory message nearly instantly after training start. I use a Geforce GTX 1080TI with 11 gigabyte memory and Cuda 9.0. My question is:

- What setup did you use for training?
- How can I reduce the memory load during training?

Thanks for your help.

Edit: When I reduce the batch size to 6 I have a 10,4 GB of my GPU memory used which is fine. So I guess that is the solution.

Stack trace is:

```
(flowavenet) C:\Users\admin\FloWaveNet>python train.py --model_name flowavenet --batch_size 8 --n_block 8 --n_flow 6 --n_layer 2 --causal no
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    training_epoch_loss = train(epoch, model, optimizer)
  File "train.py", line 108, in train
    log_p, logdet = model(x, c)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\model.py", line 195, in forward
    out, c, logdet_new = block(out, c)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\model.py", line 150, in forward
    out, c, det = flow(out, c)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\model.py", line 114, in forward
    out, det = self.coupling(out, c)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\model.py", line 74, in forward
    log_s, t = self.net(in_a, c_a).chunk(2, 1)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\modules.py", line 117, in forward
    h, s = f(h, c)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\modules.py", line 71, in forward
    h_gate = self.gate_conv(tensor)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\FloWaveNet\modules.py", line 21, in forward
    out = self.conv(tensor)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\Anaconda3\envs\flowavenet\lib\site-packages\torch\nn\modules\conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
```

**Comment by L0SG** [comment]
Yes you may need to adjust the batch size accordingly to fit all the tensors to your VRAM.

The default hyperparameter set is targeted for modern TITAN GPUs which have 12GB VRAM.
